### ISSUE TITLE
Add support for traefik v2 and web access

### ISSUE THREAD

**Issue by seb2point0** [ethibox/awesome-stacks#3]
Hi, I would be great to see support for Traefik 2 and have the ability to easily enable web access to Traefik's monitoring tools. 

Beers on me ;)

**Comment by johackim** [comment]
Hello @seb2point0

I added the support of Traefik v2 ;)

**Comment by danielpetrica** [comment]
> Hello @seb2point0
> 
> I added the support of Traefik v2 ;)

Is the web access to traefik admin included?
